---
root: true

env:
  node: true
  browser: true
  es2021: true

parser: "@babel/eslint-parser"

extends:
  - 'airbnb-base'
overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions:
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  max-len: [2, 120]